import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# >>>>>>>>>>>>>>>             README, pls          <<<<<<<<<<<<<<< #

'''This script is used for vatulazation the stats/*csv files 

generated by dyGiLa write_energies() func.
''' 

# >>>>>>>>>>>>> load the *csv files into numpy array <<<<<<<<<<<<< #

# with open('measure-stream.csv') as t_mesures:
#     mesure_data = csv.reader(t_mesures, delimiter=' ')

measureData_h30mT_tauQ300_pbBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ300-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ450_pbBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ450-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ550_pbBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ550-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ650_pbBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ650-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ750_pbBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ750-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ850_pbBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ850-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ950_pbBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ950-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ1050_pbBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ1050-H30/stats/measure-stream.csv', sep=' ', header=None)
#measureData_h30mT_tauQ1150 = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ1150-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ1250_pbBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ1250-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ1350_pbBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ1350-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ1450_pbBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ1450-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ1550_pbBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ1550-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ1650_pbBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ1650-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ1750_pbBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ1750-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ1850_pbBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ1850-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ1950_pbBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ1950-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ2050_pbBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ2050-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ2150_pbBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ2150-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ2250_pbBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ2250-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ2350_pbBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ2350-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ2450_pbBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ2450-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ2550_pbBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ2550-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ2650_pbBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ2650-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ2750_pbBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ2750-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ2850_pbBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ2850-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ2950_pbBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ2950-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ3050_pbBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-pairBreakingBC/tauQ3050-H30/stats/measure-stream.csv', sep=' ', header=None)


#measureData_h30mT_tauQ125 = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ125-H30/stats/measure-stream-run-1.csv', sep=' ', header=None)
measureData_h30mT_tauQ300_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ300-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ450_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ450-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ550_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ550-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ650_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ650-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ750_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ750-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ850_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ850-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ950_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ950-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ1050_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ1050-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ1150_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ1150-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ1250_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ1250-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ1350_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ1350-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ1450_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ1450-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ1550_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ1550-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ1650_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ1650-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ1750_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ1750-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ1850_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ1850-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ1950_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ1950-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ2050_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ2050-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ2150_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ2150-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ2250_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ2250-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ2350_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ2350-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ2450_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ2450-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ2550_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ2550-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ2650_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ2650-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ2750_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ2750-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ2850_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ2850-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ2950_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ2950-H30/stats/measure-stream.csv', sep=' ', header=None)
measureData_h30mT_tauQ3050_pBC = pd.read_csv('/home/heidi/Documents/dyGiLa-project/dyGiLa-data/dyGiLa-Langevin/thermal-bath-UniT-Hfield-quenches/tauQ125-tauQ3000-H30-RSeed-1-periodicBC/tauQ3050-H30/stats/measure-stream.csv', sep=' ', header=None)

allDatalist_pbBC = [measureData_h30mT_tauQ300_pbBC, measureData_h30mT_tauQ450_pbBC, measureData_h30mT_tauQ550_pbBC, measureData_h30mT_tauQ650_pbBC, measureData_h30mT_tauQ750_pbBC, measureData_h30mT_tauQ850_pbBC, measureData_h30mT_tauQ950_pbBC, measureData_h30mT_tauQ1050_pbBC, measureData_h30mT_tauQ1250_pbBC, measureData_h30mT_tauQ1350_pbBC, measureData_h30mT_tauQ1450_pbBC, measureData_h30mT_tauQ1550_pbBC, measureData_h30mT_tauQ1650_pbBC, measureData_h30mT_tauQ1750_pbBC, measureData_h30mT_tauQ1850_pbBC, measureData_h30mT_tauQ1950_pbBC, measureData_h30mT_tauQ2050_pbBC, measureData_h30mT_tauQ2150_pbBC, measureData_h30mT_tauQ2250_pbBC, measureData_h30mT_tauQ2350_pbBC, measureData_h30mT_tauQ2450_pbBC, measureData_h30mT_tauQ2550_pbBC, measureData_h30mT_tauQ2650_pbBC, measureData_h30mT_tauQ2750_pbBC, measureData_h30mT_tauQ2850_pbBC, measureData_h30mT_tauQ2950_pbBC, measureData_h30mT_tauQ3050_pbBC]


allDatalist_pBC = [measureData_h30mT_tauQ300_pBC, measureData_h30mT_tauQ450_pBC, measureData_h30mT_tauQ550_pBC, measureData_h30mT_tauQ650_pBC, measureData_h30mT_tauQ750_pBC, measureData_h30mT_tauQ850_pBC, measureData_h30mT_tauQ950_pBC, measureData_h30mT_tauQ1050_pBC, measureData_h30mT_tauQ1150_pBC, measureData_h30mT_tauQ1250_pBC, measureData_h30mT_tauQ1350_pBC, measureData_h30mT_tauQ1450_pBC, measureData_h30mT_tauQ1550_pBC, measureData_h30mT_tauQ1650_pBC, measureData_h30mT_tauQ1750_pBC, measureData_h30mT_tauQ1850_pBC, measureData_h30mT_tauQ1950_pBC, measureData_h30mT_tauQ2050_pBC, measureData_h30mT_tauQ2150_pBC, measureData_h30mT_tauQ2250_pBC, measureData_h30mT_tauQ2350_pBC, measureData_h30mT_tauQ2450_pBC, measureData_h30mT_tauQ2550_pBC, measureData_h30mT_tauQ2650_pBC, measureData_h30mT_tauQ2750_pBC, measureData_h30mT_tauQ2850_pBC, measureData_h30mT_tauQ2950_pBC, measureData_h30mT_tauQ3050_pBC]

### For all *csv files, delimiter is comma * *.
### Every line corresponds to a common pressure value,
### the 0th element of every line is sim time t, gol.t in unit of tGL
### the 1st element of every line is temperature of homogenous quench (mK),
### the 2nd element of every line .

## >>>>>>>>>>>>>>>>>>> Scatter plot for A-B transition woth/without pairing breaking BC <<<<<<<<<<<<<<<<<<<< ##

tauQ_pBC = np.array([300, 450, 550, 650, 750, 850, 950, 1050, 1150, 1250, 1350, 1450, 1550, 1650, 1750, 1850, 1950, 2050, 2150, 2250, 2350, 2450, 2550, 2650, 2750, 2850, 2950, 3050])
gamma_pBC = np.full(np.shape(tauQ_pBC),0.05)

#print(eallDatalist[0].values[1999,4])
avgap_pBC = np.array([]);
for dataset in allDatalist_pBC:
    avgap_pBC = np.append(avgap_pBC, dataset.values[1999,4])
    
print(avgap_pBC)    

##

tauQ_pbBC = np.array([300, 450, 550, 650, 750, 850, 950, 1050, 1250, 1350, 1450, 1550, 1650, 1750, 1850, 1950, 2050, 2150, 2250, 2350, 2450, 2550, 2650, 2750, 2850, 2950, 3050])
gamma_pbBC = np.full(np.shape(tauQ_pbBC),0.05)

#print(eallDatalist[0].values[1999,4])
avgap_pbBC = np.array([]);
for dataset in allDatalist_pbBC:
    avgap_pbBC = np.append(avgap_pbBC, dataset.values[1999,4])
    
print(avgap_pBC)    


fig1, ax1 = plt.subplots(1,1);

ax1.scatter(1/tauQ_pBC, gamma_pBC, marker='^', s=90, c=avgap_pBC)
ax1.scatter(1/tauQ_pbBC, gamma_pbBC, marker='o', s=50, c=avgap_pbBC)




ax1.set_xscale('log')
ax1.set_xticks([10**-4, 10**-3, 10**-2])
ax1.set_xlabel(r'$t/t^{0}_{GL}$',fontsize = 18.0)
#ax1.set_ylabel(r'$\Delta_{A(B)}/k_{b}T_{c}(p)$',fontsize = 18.0)
ax1.set_ylabel(r'$T/T_{c}(p)$',fontsize = 18.0)
ax1.tick_params(axis='both', which='major', labelsize=30)


# ax1.legend(prop={'size': 18}, loc=1);
# ax1.grid(True)
# ax1.legend(prop={'size': 18}, bbox_to_anchor=(1.54, 1.0), loc='upper right')
# ax2.legend(prop={'size': 18}, bbox_to_anchor=(1.54, 0.0), loc='lower right')



plt.show()
